# Generated by Django 5.1.5 on 2026-02-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_area_boundary_polygon_landmark_ar_anchor_points"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="area",
            new_name="geo_area_city_id_eb7204_idx",
            old_name="geo_area_city_active_idx",
        ),
        migrations.RenameIndex(
            model_name="city",
            new_name="geo_city_country_69a3c8_idx",
            old_name="geo_city_country_active_idx",
        ),
        migrations.RenameIndex(
            model_name="landmark",
            new_name="geo_landmar_area_id_c01b1c_idx",
            old_name="geo_landmark_area_active_idx",
        ),
    ]
