# Generated by Django 5.1.5 on 2026-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("NEEDS_REVIEW", "Needs Review"),
                    ("FLAGGED", "Flagged"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
