# Generated by Django 5.1.5 on 2026-02-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_vendor_claimed_status_storefront_photo_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="google_place_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Google Places place_id — used for upsert deduplication on re-import",
                max_length=300,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="website_url",
            field=models.URLField(
                blank=True, default="", help_text="Business website from Google Places"
            ),
        ),
    ]
