# Generated by Django 5.1.5 on 2026-02-23 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_google_places_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="gps_baseline",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Original GPS location from data source for change detection.",
                null=True,
                srid=4326,
            ),
        ),
    ]
