# Generated by Django 5.1.5 on 2026-02-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_google_places_fields"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="google_places_batches",
                to="geo.area",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="import_type",
            field=models.CharField(
                choices=[("CSV", "CSV Upload"), ("GOOGLE_PLACES", "Google Places API")],
                db_index=True,
                default="CSV",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="radius_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="search_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="search_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="search_query",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="file_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key ONLY — never a public URL.",
                max_length=500,
            ),
        ),
    ]
