# Generated by Django 5.1.5 on 2026-02-23 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_google_places_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="System imports (Google Places) have created_by=None",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
