# Generated by Django 5.1.5 on 2026-02-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0003_importbatch_metadata_processed_place_ids"),
        ("imports", "0003_make_created_by_nullable"),
    ]

    operations = []
