# Generated by Django 5.1.5 on 2026-02-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_merge_20260224_1502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("CSV", "CSV Upload"),
                    ("GOOGLE_PLACES", "Google Places API"),
                    ("GOOGLE_PLACES_ENHANCED", "Google Places Enhanced"),
                ],
                db_index=True,
                default="CSV",
                max_length=30,
            ),
        ),
    ]
