"""
AirAd Backend — Accounts Serializers

CustomTokenObtainPairSerializer adds role, full_name, email to JWT claims.
LoginSerializer validates credentials and delegates to services.py.
No business logic here — validation only.
"""

import logging

from rest_framework import serializers
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.tokens import Token

from .models import AdminRole, AdminUser

logger = logging.getLogger(__name__)


class CustomTokenObtainPairSerializer(TokenObtainPairSerializer):
    """JWT token serializer that injects extra claims into the access token.

    Adds role, full_name, and email to the JWT payload so clients
    can read user context without an extra API call.
    """

    @classmethod
    def get_token(cls, user: AdminUser) -> Token:
        """Build the JWT token with additional AirAd-specific claims.

        Args:
            user: The authenticated AdminUser instance.

        Returns:
            JWT Token with role, full_name, and email claims added.
        """
        token = super().get_token(user)
        token["role"] = user.role
        token["full_name"] = user.full_name
        token["email"] = user.email
        return token


class LoginSerializer(serializers.Serializer):
    """Serializer for the login endpoint.

    Validates that email and password are present.
    Business logic (lockout, credential check) is in services.py.
    """

    email = serializers.EmailField()
    password = serializers.CharField(write_only=True, style={"input_type": "password"})


class LogoutSerializer(serializers.Serializer):
    """Serializer for the logout endpoint.

    Requires the refresh token to blacklist it.
    """

    refresh = serializers.CharField(help_text="The refresh token to invalidate.")


class AdminUserSerializer(serializers.ModelSerializer):
    """Read-only serializer for AdminUser — used in JWT response and profile views."""

    is_locked = serializers.SerializerMethodField()
    failed_attempts = serializers.IntegerField(
        source="failed_login_count", read_only=True
    )

    def get_is_locked(self, obj: AdminUser) -> bool:
        return obj.is_locked()

    class Meta:
        model = AdminUser
        fields = [
            "id",
            "email",
            "full_name",
            "role",
            "is_active",
            "is_locked",
            "failed_attempts",
            "locked_until",
            "must_change_password",
            "last_login",
            "last_login_ip",
            "created_at",
            "updated_at",
        ]
        read_only_fields = fields


class UpdateAdminUserSerializer(serializers.Serializer):
    """Serializer for PATCH /api/v1/auth/users/<pk>/ (SUPER_ADMIN only).

    All fields optional — only provided fields are updated.
    failed_attempts maps to failed_login_count on the model.
    """

    full_name = serializers.CharField(max_length=255, required=False)
    role = serializers.ChoiceField(choices=[r.value for r in AdminRole], required=False)
    is_active = serializers.BooleanField(required=False)
    is_locked = serializers.BooleanField(required=False)
    failed_attempts = serializers.IntegerField(
        source="failed_login_count",
        required=False,
        min_value=0,
    )


class CreateAdminUserSerializer(serializers.Serializer):
    """Serializer for creating a new AdminUser (SUPER_ADMIN only).

    Password is auto-generated by services.py — not required in the request.
    No business logic — delegates to accounts/services.py.
    """

    email = serializers.EmailField()
    full_name = serializers.CharField(max_length=255)
    role = serializers.ChoiceField(choices=[r.value for r in AdminRole])
